/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interpretebd;

import java.awt.CardLayout;

/**
 *
 * @author Jurgenn
 */
public class InterpreteGUI extends javax.swing.JFrame {

    CardLayout c;
    
    /**
     * Creates new form InterpreteGUI
     */
    public InterpreteGUI() {
        initComponents();
        setResizable(false);
        c = (CardLayout) getContentPane().getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        login_titleLabel = new javax.swing.JLabel();
        login_subTitleLabel = new javax.swing.JLabel();
        login_serverLabel = new javax.swing.JLabel();
        login_userLabel = new javax.swing.JLabel();
        login_passLabel = new javax.swing.JLabel();
        login_dbNameLabel = new javax.swing.JLabel();
        login_serverText = new javax.swing.JTextField();
        login_userText = new javax.swing.JTextField();
        login_passText = new javax.swing.JTextField();
        login_dbText = new javax.swing.JTextField();
        login_connectButton = new javax.swing.JButton();
        login_helpButton = new javax.swing.JButton();
        login_exitButton = new javax.swing.JButton();
        login_aboutButton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        aboutPanel = new javax.swing.JPanel();
        about_titleLabel = new javax.swing.JLabel();
        about_nameLabel = new javax.swing.JLabel();
        about_verLabel = new javax.swing.JLabel();
        about_creationLabel = new javax.swing.JLabel();
        about_authorLabel = new javax.swing.JLabel();
        about_homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        login_titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_titleLabel.setText("Interprete de Algebra Relacional");

        login_subTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_subTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_subTitleLabel.setText("Login");

        login_serverLabel.setText("Servidor:");

        login_userLabel.setText("Usuario:");

        login_passLabel.setText("Contraseña:");

        login_dbNameLabel.setText("Base de datos:");

        login_connectButton.setText("Conectar");
        login_connectButton.setPreferredSize(new java.awt.Dimension(89, 25));

        login_helpButton.setText("Ayuda");
        login_helpButton.setMaximumSize(new java.awt.Dimension(89, 25));
        login_helpButton.setMinimumSize(new java.awt.Dimension(89, 25));
        login_helpButton.setPreferredSize(new java.awt.Dimension(89, 25));

        login_exitButton.setText("Salir");
        login_exitButton.setPreferredSize(new java.awt.Dimension(89, 25));
        login_exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_exitButtonActionPerformed(evt);
            }
        });

        login_aboutButton.setText("Acerca de");
        login_aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login_subTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_serverLabel)
                    .addComponent(login_userLabel)
                    .addComponent(login_passLabel)
                    .addComponent(login_dbNameLabel))
                .addGap(20, 20, 20)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_dbText, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(login_serverText)
                        .addComponent(login_userText)
                        .addComponent(login_passText, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addGap(160, 160, 160))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(login_exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_aboutButton)
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(login_titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(login_subTitleLabel)
                .addGap(60, 60, 60)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_serverText)
                    .addComponent(login_serverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_userText)
                    .addComponent(login_userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_passText)
                    .addComponent(login_passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_dbText)
                    .addComponent(login_dbNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(login_connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_aboutButton))
                .addContainerGap())
        );

        getContentPane().add(loginPanel, "loginCard");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(homePanel, "homeCard");

        about_titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        about_titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about_titleLabel.setText("Acerca de");

        about_nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        about_nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about_nameLabel.setText("Interprete de Algebra Relacional");

        about_verLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about_verLabel.setText("Version 1.5");

        about_creationLabel.setText("Creado el 25 de setiembre del 2017");

        about_authorLabel.setText("Jurgenn Morales Jimenez");

        about_homeButton.setText("Regresar");
        about_homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(about_titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(about_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(about_verLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(about_homeButton)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(about_creationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(about_authorLabel)
                .addContainerGap())
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(about_titleLabel)
                .addGap(121, 121, 121)
                .addComponent(about_nameLabel)
                .addGap(41, 41, 41)
                .addComponent(about_verLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(about_homeButton)
                .addGap(122, 122, 122)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(about_authorLabel)
                    .addComponent(about_creationLabel))
                .addContainerGap())
        );

        getContentPane().add(aboutPanel, "aboutCard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void about_homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_homeButtonActionPerformed
       c.show(this.getContentPane(), "loginCard");
    }//GEN-LAST:event_about_homeButtonActionPerformed

    private void login_aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_aboutButtonActionPerformed
        c.show(this.getContentPane(), "aboutCard");
    }//GEN-LAST:event_login_aboutButtonActionPerformed

    private void login_exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_login_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterpreteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterpreteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterpreteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterpreteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterpreteGUI a = new InterpreteGUI();
                a.pack();
                a.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel about_authorLabel;
    private javax.swing.JLabel about_creationLabel;
    private javax.swing.JButton about_homeButton;
    private javax.swing.JLabel about_nameLabel;
    private javax.swing.JLabel about_titleLabel;
    private javax.swing.JLabel about_verLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton login_aboutButton;
    private javax.swing.JButton login_connectButton;
    private javax.swing.JLabel login_dbNameLabel;
    private javax.swing.JTextField login_dbText;
    private javax.swing.JButton login_exitButton;
    private javax.swing.JButton login_helpButton;
    private javax.swing.JLabel login_passLabel;
    private javax.swing.JTextField login_passText;
    private javax.swing.JLabel login_serverLabel;
    private javax.swing.JTextField login_serverText;
    private javax.swing.JLabel login_subTitleLabel;
    private javax.swing.JLabel login_titleLabel;
    private javax.swing.JLabel login_userLabel;
    private javax.swing.JTextField login_userText;
    // End of variables declaration//GEN-END:variables
}
